#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDoAn")]
	public partial class dbQLDADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertDoan(Doan instance);
    partial void UpdateDoan(Doan instance);
    partial void DeleteDoan(Doan instance);
    partial void InsertGvhd(Gvhd instance);
    partial void UpdateGvhd(Gvhd instance);
    partial void DeleteGvhd(Gvhd instance);
    partial void InsertNhom(Nhom instance);
    partial void UpdateNhom(Nhom instance);
    partial void DeleteNhom(Nhom instance);
    partial void InsertPtda(Ptda instance);
    partial void UpdatePtda(Ptda instance);
    partial void DeletePtda(Ptda instance);
    partial void InsertSinhvien(Sinhvien instance);
    partial void UpdateSinhvien(Sinhvien instance);
    partial void DeleteSinhvien(Sinhvien instance);
    #endregion
		
		public dbQLDADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyDoAnConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLDADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Doan> Doans
		{
			get
			{
				return this.GetTable<Doan>();
			}
		}
		
		public System.Data.Linq.Table<Gvhd> Gvhds
		{
			get
			{
				return this.GetTable<Gvhd>();
			}
		}
		
		public System.Data.Linq.Table<Nhom> Nhoms
		{
			get
			{
				return this.GetTable<Nhom>();
			}
		}
		
		public System.Data.Linq.Table<Ptda> Ptdas
		{
			get
			{
				return this.GetTable<Ptda>();
			}
		}
		
		public System.Data.Linq.Table<Sinhvien> Sinhviens
		{
			get
			{
				return this.GetTable<Sinhvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NChar(16)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doan")]
	public partial class Doan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mada;
		
		private string _Tenda;
		
		private System.Nullable<System.DateTime> _Thoigianbd;
		
		private System.Nullable<System.DateTime> _Thoigiankt;
		
		private EntitySet<Ptda> _Ptdas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadaChanging(int value);
    partial void OnMadaChanged();
    partial void OnTendaChanging(string value);
    partial void OnTendaChanged();
    partial void OnThoigianbdChanging(System.Nullable<System.DateTime> value);
    partial void OnThoigianbdChanged();
    partial void OnThoigianktChanging(System.Nullable<System.DateTime> value);
    partial void OnThoigianktChanged();
    #endregion
		
		public Doan()
		{
			this._Ptdas = new EntitySet<Ptda>(new Action<Ptda>(this.attach_Ptdas), new Action<Ptda>(this.detach_Ptdas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mada", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mada
		{
			get
			{
				return this._Mada;
			}
			set
			{
				if ((this._Mada != value))
				{
					this.OnMadaChanging(value);
					this.SendPropertyChanging();
					this._Mada = value;
					this.SendPropertyChanged("Mada");
					this.OnMadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenda", DbType="NVarChar(50)")]
		public string Tenda
		{
			get
			{
				return this._Tenda;
			}
			set
			{
				if ((this._Tenda != value))
				{
					this.OnTendaChanging(value);
					this.SendPropertyChanging();
					this._Tenda = value;
					this.SendPropertyChanged("Tenda");
					this.OnTendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianbd", DbType="Date")]
		public System.Nullable<System.DateTime> Thoigianbd
		{
			get
			{
				return this._Thoigianbd;
			}
			set
			{
				if ((this._Thoigianbd != value))
				{
					this.OnThoigianbdChanging(value);
					this.SendPropertyChanging();
					this._Thoigianbd = value;
					this.SendPropertyChanged("Thoigianbd");
					this.OnThoigianbdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigiankt", DbType="Date")]
		public System.Nullable<System.DateTime> Thoigiankt
		{
			get
			{
				return this._Thoigiankt;
			}
			set
			{
				if ((this._Thoigiankt != value))
				{
					this.OnThoigianktChanging(value);
					this.SendPropertyChanging();
					this._Thoigiankt = value;
					this.SendPropertyChanged("Thoigiankt");
					this.OnThoigianktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_Ptda", Storage="_Ptdas", ThisKey="Mada", OtherKey="Mada")]
		public EntitySet<Ptda> Ptdas
		{
			get
			{
				return this._Ptdas;
			}
			set
			{
				this._Ptdas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Doan = this;
		}
		
		private void detach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Doan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gvhd")]
	public partial class Gvhd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Magv;
		
		private string _Matkhau;
		
		private string _Hotengv;
		
		private string _Email;
		
		private System.Nullable<int> _Mada;
		
		private EntitySet<Ptda> _Ptdas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMagvChanging(int value);
    partial void OnMagvChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnHotengvChanging(string value);
    partial void OnHotengvChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMadaChanging(System.Nullable<int> value);
    partial void OnMadaChanged();
    #endregion
		
		public Gvhd()
		{
			this._Ptdas = new EntitySet<Ptda>(new Action<Ptda>(this.attach_Ptdas), new Action<Ptda>(this.detach_Ptdas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magv", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Magv
		{
			get
			{
				return this._Magv;
			}
			set
			{
				if ((this._Magv != value))
				{
					this.OnMagvChanging(value);
					this.SendPropertyChanging();
					this._Magv = value;
					this.SendPropertyChanged("Magv");
					this.OnMagvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotengv", DbType="NVarChar(150)")]
		public string Hotengv
		{
			get
			{
				return this._Hotengv;
			}
			set
			{
				if ((this._Hotengv != value))
				{
					this.OnHotengvChanging(value);
					this.SendPropertyChanging();
					this._Hotengv = value;
					this.SendPropertyChanged("Hotengv");
					this.OnHotengvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mada", DbType="Int")]
		public System.Nullable<int> Mada
		{
			get
			{
				return this._Mada;
			}
			set
			{
				if ((this._Mada != value))
				{
					this.OnMadaChanging(value);
					this.SendPropertyChanging();
					this._Mada = value;
					this.SendPropertyChanged("Mada");
					this.OnMadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gvhd_Ptda", Storage="_Ptdas", ThisKey="Magv", OtherKey="Mada")]
		public EntitySet<Ptda> Ptdas
		{
			get
			{
				return this._Ptdas;
			}
			set
			{
				this._Ptdas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Gvhd = this;
		}
		
		private void detach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Gvhd = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom")]
	public partial class Nhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Manhom;
		
		private string _Tennhom;
		
		private EntityRef<Sinhvien> _Sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhomChanging(int value);
    partial void OnManhomChanged();
    partial void OnTennhomChanging(string value);
    partial void OnTennhomChanged();
    #endregion
		
		public Nhom()
		{
			this._Sinhvien = default(EntityRef<Sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					if (this._Sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhom", DbType="NVarChar(50)")]
		public string Tennhom
		{
			get
			{
				return this._Tennhom;
			}
			set
			{
				if ((this._Tennhom != value))
				{
					this.OnTennhomChanging(value);
					this.SendPropertyChanging();
					this._Tennhom = value;
					this.SendPropertyChanged("Tennhom");
					this.OnTennhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Nhom", Storage="_Sinhvien", ThisKey="Manhom", OtherKey="Id", IsForeignKey=true)]
		public Sinhvien Sinhvien
		{
			get
			{
				return this._Sinhvien.Entity;
			}
			set
			{
				Sinhvien previousValue = this._Sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._Sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sinhvien.Entity = null;
						previousValue.Nhom = null;
					}
					this._Sinhvien.Entity = value;
					if ((value != null))
					{
						value.Nhom = this;
						this._Manhom = value.Id;
					}
					else
					{
						this._Manhom = default(int);
					}
					this.SendPropertyChanged("Sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ptda")]
	public partial class Ptda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _Magv;
		
		private int _Mada;
		
		private int _Mssv;
		
		private System.Nullable<int> _Diem;
		
		private EntityRef<Doan> _Doan;
		
		private EntityRef<Gvhd> _Gvhd;
		
		private EntityRef<Sinhvien> _Sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMagvChanging(System.Nullable<int> value);
    partial void OnMagvChanged();
    partial void OnMadaChanging(int value);
    partial void OnMadaChanged();
    partial void OnMssvChanging(int value);
    partial void OnMssvChanged();
    partial void OnDiemChanging(System.Nullable<int> value);
    partial void OnDiemChanged();
    #endregion
		
		public Ptda()
		{
			this._Doan = default(EntityRef<Doan>);
			this._Gvhd = default(EntityRef<Gvhd>);
			this._Sinhvien = default(EntityRef<Sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magv", DbType="Int")]
		public System.Nullable<int> Magv
		{
			get
			{
				return this._Magv;
			}
			set
			{
				if ((this._Magv != value))
				{
					this.OnMagvChanging(value);
					this.SendPropertyChanging();
					this._Magv = value;
					this.SendPropertyChanged("Magv");
					this.OnMagvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mada", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mada
		{
			get
			{
				return this._Mada;
			}
			set
			{
				if ((this._Mada != value))
				{
					if ((this._Doan.HasLoadedOrAssignedValue || this._Gvhd.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadaChanging(value);
					this.SendPropertyChanging();
					this._Mada = value;
					this.SendPropertyChanged("Mada");
					this.OnMadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mssv", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Mssv
		{
			get
			{
				return this._Mssv;
			}
			set
			{
				if ((this._Mssv != value))
				{
					if (this._Sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMssvChanging(value);
					this.SendPropertyChanging();
					this._Mssv = value;
					this.SendPropertyChanged("Mssv");
					this.OnMssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Int")]
		public System.Nullable<int> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_Ptda", Storage="_Doan", ThisKey="Mada", OtherKey="Mada", IsForeignKey=true)]
		public Doan Doan
		{
			get
			{
				return this._Doan.Entity;
			}
			set
			{
				Doan previousValue = this._Doan.Entity;
				if (((previousValue != value) 
							|| (this._Doan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Doan.Entity = null;
						previousValue.Ptdas.Remove(this);
					}
					this._Doan.Entity = value;
					if ((value != null))
					{
						value.Ptdas.Add(this);
						this._Mada = value.Mada;
					}
					else
					{
						this._Mada = default(int);
					}
					this.SendPropertyChanged("Doan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gvhd_Ptda", Storage="_Gvhd", ThisKey="Mada", OtherKey="Magv", IsForeignKey=true)]
		public Gvhd Gvhd
		{
			get
			{
				return this._Gvhd.Entity;
			}
			set
			{
				Gvhd previousValue = this._Gvhd.Entity;
				if (((previousValue != value) 
							|| (this._Gvhd.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gvhd.Entity = null;
						previousValue.Ptdas.Remove(this);
					}
					this._Gvhd.Entity = value;
					if ((value != null))
					{
						value.Ptdas.Add(this);
						this._Mada = value.Magv;
					}
					else
					{
						this._Mada = default(int);
					}
					this.SendPropertyChanged("Gvhd");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Ptda", Storage="_Sinhvien", ThisKey="Mssv", OtherKey="Id", IsForeignKey=true)]
		public Sinhvien Sinhvien
		{
			get
			{
				return this._Sinhvien.Entity;
			}
			set
			{
				Sinhvien previousValue = this._Sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._Sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sinhvien.Entity = null;
						previousValue.Ptdas.Remove(this);
					}
					this._Sinhvien.Entity = value;
					if ((value != null))
					{
						value.Ptdas.Add(this);
						this._Mssv = value.Id;
					}
					else
					{
						this._Mssv = default(int);
					}
					this.SendPropertyChanged("Sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sinhvien")]
	public partial class Sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Hoten;
		
		private string _Matkhau;
		
		private string _Email;
		
		private System.Nullable<bool> _Gioitinh;
		
		private System.Nullable<int> _Manhom;
		
		private string _Taikhoan;
		
		private string _Sdt;
		
		private string _Hinh;
		
		private int _Id;
		
		private EntityRef<Nhom> _Nhom;
		
		private EntitySet<Ptda> _Ptdas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnManhomChanging(System.Nullable<int> value);
    partial void OnManhomChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Sinhvien()
		{
			this._Nhom = default(EntityRef<Nhom>);
			this._Ptdas = new EntitySet<Ptda>(new Action<Ptda>(this.attach_Ptdas), new Action<Ptda>(this.detach_Ptdas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="Int")]
		public System.Nullable<int> Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(20)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Nhom", Storage="_Nhom", ThisKey="Id", OtherKey="Manhom", IsUnique=true, IsForeignKey=false)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.Sinhvien = null;
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.Sinhvien = this;
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Ptda", Storage="_Ptdas", ThisKey="Id", OtherKey="Mssv")]
		public EntitySet<Ptda> Ptdas
		{
			get
			{
				return this._Ptdas;
			}
			set
			{
				this._Ptdas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Sinhvien = this;
		}
		
		private void detach_Ptdas(Ptda entity)
		{
			this.SendPropertyChanging();
			entity.Sinhvien = null;
		}
	}
}
#pragma warning restore 1591
