<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDoAn" Class="dbQLDADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=QuanLyDoAn;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyDoAnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Taikhoan" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doan" Member="Doans">
    <Type Name="Doan">
      <Column Name="Mada" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenda" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Doan_Ptda" Member="Ptdas" ThisKey="Mada" OtherKey="Mada" Type="Ptda" />
    </Type>
  </Table>
  <Table Name="dbo.Gvhd" Member="Gvhds">
    <Type Name="Gvhd">
      <Column Name="Magv" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Hotengv" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Mada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Gvhd_Ptda" Member="Ptdas" ThisKey="Magv" OtherKey="Mada" Type="Ptda" />
    </Type>
  </Table>
  <Table Name="dbo.Nhom" Member="Nhoms">
    <Type Name="Nhom">
      <Column Name="Manhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tennhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Sinhvien_Nhom" Member="Sinhvien" ThisKey="Manhom" OtherKey="Id" Type="Sinhvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ptda" Member="Ptdas">
    <Type Name="Ptda">
      <Column Name="Magv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mada" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mssv" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Doan_Ptda" Member="Doan" ThisKey="Mada" OtherKey="Mada" Type="Doan" IsForeignKey="true" />
      <Association Name="Gvhd_Ptda" Member="Gvhd" ThisKey="Mada" OtherKey="Magv" Type="Gvhd" IsForeignKey="true" />
      <Association Name="Sinhvien_Ptda" Member="Sinhvien" ThisKey="Mssv" OtherKey="Id" Type="Sinhvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sinhvien" Member="Sinhviens">
    <Type Name="Sinhvien">
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Manhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Taikhoan" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Hinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Sinhvien_Nhom" Member="Nhom" ThisKey="Id" OtherKey="Manhom" Type="Nhom" Cardinality="One" />
      <Association Name="Sinhvien_Ptda" Member="Ptdas" ThisKey="Id" OtherKey="Mssv" Type="Ptda" />
    </Type>
  </Table>
</Database>