//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doan()
        {
            this.ptdas = new HashSet<ptda>();
        }
    
        public string Mada { get; set; }
        public string Tenda { get; set; }
        public Nullable<System.DateTime> Thoigianbd { get; set; }
        public Nullable<System.DateTime> Thoigiankt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptda> ptdas { get; set; }
    }
}
