//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gvhd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gvhd()
        {
            this.ptdas = new HashSet<ptda>();
        }
    
        public string Magv { get; set; }
        public string Matkhau { get; set; }
        public string Hotengv { get; set; }
        public string Email { get; set; }
        public string Mada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptda> ptdas { get; set; }
    }
}
