//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptda
    {
        public string Magv { get; set; }
        public string Mada { get; set; }
        public string Mssv { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual gvhd gvhd { get; set; }
        public virtual sinhvien sinhvien { get; set; }
    }
}
