//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDoAnEntities2 : DbContext
    {
        public QuanLyDoAnEntities2()
            : base("name=QuanLyDoAnEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<doan> doans { get; set; }
        public virtual DbSet<gvhd> gvhds { get; set; }
        public virtual DbSet<nhom> nhoms { get; set; }
        public virtual DbSet<ptda> ptdas { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
    }
}
