#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDoAn")]
	public partial class QLDADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertnhom(nhom instance);
    partial void Updatenhom(nhom instance);
    partial void Deletenhom(nhom instance);
    partial void Insertgvhd(gvhd instance);
    partial void Updategvhd(gvhd instance);
    partial void Deletegvhd(gvhd instance);
    partial void Insertdoan(doan instance);
    partial void Updatedoan(doan instance);
    partial void Deletedoan(doan instance);
    partial void Insertptda(ptda instance);
    partial void Updateptda(ptda instance);
    partial void Deleteptda(ptda instance);
    partial void Insertsinhvien(sinhvien instance);
    partial void Updatesinhvien(sinhvien instance);
    partial void Deletesinhvien(sinhvien instance);
    #endregion
		
		public QLDADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyDoAnConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<nhom> nhoms
		{
			get
			{
				return this.GetTable<nhom>();
			}
		}
		
		public System.Data.Linq.Table<gvhd> gvhds
		{
			get
			{
				return this.GetTable<gvhd>();
			}
		}
		
		public System.Data.Linq.Table<doan> doans
		{
			get
			{
				return this.GetTable<doan>();
			}
		}
		
		public System.Data.Linq.Table<ptda> ptdas
		{
			get
			{
				return this.GetTable<ptda>();
			}
		}
		
		public System.Data.Linq.Table<sinhvien> sinhviens
		{
			get
			{
				return this.GetTable<sinhvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taikhoan;
		
		private string _matkhua;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhuaChanging(string value);
    partial void OnmatkhuaChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhua", DbType="NChar(16)")]
		public string matkhua
		{
			get
			{
				return this._matkhua;
			}
			set
			{
				if ((this._matkhua != value))
				{
					this.OnmatkhuaChanging(value);
					this.SendPropertyChanging();
					this._matkhua = value;
					this.SendPropertyChanged("matkhua");
					this.OnmatkhuaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhom")]
	public partial class nhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhom;
		
		private string _mssv;
		
		private EntitySet<sinhvien> _sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhomChanging(string value);
    partial void OnmanhomChanged();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    #endregion
		
		public nhom()
		{
			this._sinhviens = new EntitySet<sinhvien>(new Action<sinhvien>(this.attach_sinhviens), new Action<sinhvien>(this.detach_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhom", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhom
		{
			get
			{
				return this._manhom;
			}
			set
			{
				if ((this._manhom != value))
				{
					this.OnmanhomChanging(value);
					this.SendPropertyChanging();
					this._manhom = value;
					this.SendPropertyChanged("manhom");
					this.OnmanhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhom_sinhvien", Storage="_sinhviens", ThisKey="manhom", OtherKey="manhom")]
		public EntitySet<sinhvien> sinhviens
		{
			get
			{
				return this._sinhviens;
			}
			set
			{
				this._sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.nhom = this;
		}
		
		private void detach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.nhom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gvhd")]
	public partial class gvhd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _magv;
		
		private string _matkhau;
		
		private string _hotengv;
		
		private string _email;
		
		private string _mada;
		
		private EntitySet<ptda> _ptdas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmagvChanging(string value);
    partial void OnmagvChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotengvChanging(string value);
    partial void OnhotengvChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmadaChanging(string value);
    partial void OnmadaChanged();
    #endregion
		
		public gvhd()
		{
			this._ptdas = new EntitySet<ptda>(new Action<ptda>(this.attach_ptdas), new Action<ptda>(this.detach_ptdas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magv", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string magv
		{
			get
			{
				return this._magv;
			}
			set
			{
				if ((this._magv != value))
				{
					this.OnmagvChanging(value);
					this.SendPropertyChanging();
					this._magv = value;
					this.SendPropertyChanged("magv");
					this.OnmagvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NChar(16)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotengv", DbType="NVarChar(150)")]
		public string hotengv
		{
			get
			{
				return this._hotengv;
			}
			set
			{
				if ((this._hotengv != value))
				{
					this.OnhotengvChanging(value);
					this.SendPropertyChanging();
					this._hotengv = value;
					this.SendPropertyChanged("hotengv");
					this.OnhotengvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mada", DbType="NChar(10)")]
		public string mada
		{
			get
			{
				return this._mada;
			}
			set
			{
				if ((this._mada != value))
				{
					this.OnmadaChanging(value);
					this.SendPropertyChanging();
					this._mada = value;
					this.SendPropertyChanged("mada");
					this.OnmadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gvhd_ptda", Storage="_ptdas", ThisKey="magv", OtherKey="magv")]
		public EntitySet<ptda> ptdas
		{
			get
			{
				return this._ptdas;
			}
			set
			{
				this._ptdas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.gvhd = this;
		}
		
		private void detach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.gvhd = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.doan")]
	public partial class doan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mada;
		
		private string _tenda;
		
		private System.Nullable<System.DateTime> _thoigianbd;
		
		private System.Nullable<System.DateTime> _thoigiankt;
		
		private EntitySet<ptda> _ptdas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadaChanging(string value);
    partial void OnmadaChanged();
    partial void OntendaChanging(string value);
    partial void OntendaChanged();
    partial void OnthoigianbdChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigianbdChanged();
    partial void OnthoigianktChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigianktChanged();
    #endregion
		
		public doan()
		{
			this._ptdas = new EntitySet<ptda>(new Action<ptda>(this.attach_ptdas), new Action<ptda>(this.detach_ptdas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mada", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mada
		{
			get
			{
				return this._mada;
			}
			set
			{
				if ((this._mada != value))
				{
					this.OnmadaChanging(value);
					this.SendPropertyChanging();
					this._mada = value;
					this.SendPropertyChanged("mada");
					this.OnmadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenda", DbType="NVarChar(50)")]
		public string tenda
		{
			get
			{
				return this._tenda;
			}
			set
			{
				if ((this._tenda != value))
				{
					this.OntendaChanging(value);
					this.SendPropertyChanging();
					this._tenda = value;
					this.SendPropertyChanged("tenda");
					this.OntendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianbd", DbType="Date")]
		public System.Nullable<System.DateTime> thoigianbd
		{
			get
			{
				return this._thoigianbd;
			}
			set
			{
				if ((this._thoigianbd != value))
				{
					this.OnthoigianbdChanging(value);
					this.SendPropertyChanging();
					this._thoigianbd = value;
					this.SendPropertyChanged("thoigianbd");
					this.OnthoigianbdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigiankt", DbType="Date")]
		public System.Nullable<System.DateTime> thoigiankt
		{
			get
			{
				return this._thoigiankt;
			}
			set
			{
				if ((this._thoigiankt != value))
				{
					this.OnthoigianktChanging(value);
					this.SendPropertyChanging();
					this._thoigiankt = value;
					this.SendPropertyChanged("thoigiankt");
					this.OnthoigianktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doan_ptda", Storage="_ptdas", ThisKey="mada", OtherKey="mada")]
		public EntitySet<ptda> ptdas
		{
			get
			{
				return this._ptdas;
			}
			set
			{
				this._ptdas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.doan = this;
		}
		
		private void detach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.doan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ptda")]
	public partial class ptda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _magv;
		
		private string _mada;
		
		private string _mssv;
		
		private System.Nullable<int> _diem;
		
		private EntityRef<doan> _doan;
		
		private EntityRef<gvhd> _gvhd;
		
		private EntityRef<sinhvien> _sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmagvChanging(string value);
    partial void OnmagvChanged();
    partial void OnmadaChanging(string value);
    partial void OnmadaChanged();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    partial void OndiemChanging(System.Nullable<int> value);
    partial void OndiemChanged();
    #endregion
		
		public ptda()
		{
			this._doan = default(EntityRef<doan>);
			this._gvhd = default(EntityRef<gvhd>);
			this._sinhvien = default(EntityRef<sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magv", DbType="NChar(20)")]
		public string magv
		{
			get
			{
				return this._magv;
			}
			set
			{
				if ((this._magv != value))
				{
					if (this._gvhd.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmagvChanging(value);
					this.SendPropertyChanging();
					this._magv = value;
					this.SendPropertyChanged("magv");
					this.OnmagvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mada", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mada
		{
			get
			{
				return this._mada;
			}
			set
			{
				if ((this._mada != value))
				{
					if (this._doan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadaChanging(value);
					this.SendPropertyChanging();
					this._mada = value;
					this.SendPropertyChanged("mada");
					this.OnmadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					if (this._sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Int")]
		public System.Nullable<int> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doan_ptda", Storage="_doan", ThisKey="mada", OtherKey="mada", IsForeignKey=true)]
		public doan doan
		{
			get
			{
				return this._doan.Entity;
			}
			set
			{
				doan previousValue = this._doan.Entity;
				if (((previousValue != value) 
							|| (this._doan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._doan.Entity = null;
						previousValue.ptdas.Remove(this);
					}
					this._doan.Entity = value;
					if ((value != null))
					{
						value.ptdas.Add(this);
						this._mada = value.mada;
					}
					else
					{
						this._mada = default(string);
					}
					this.SendPropertyChanged("doan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gvhd_ptda", Storage="_gvhd", ThisKey="magv", OtherKey="magv", IsForeignKey=true)]
		public gvhd gvhd
		{
			get
			{
				return this._gvhd.Entity;
			}
			set
			{
				gvhd previousValue = this._gvhd.Entity;
				if (((previousValue != value) 
							|| (this._gvhd.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gvhd.Entity = null;
						previousValue.ptdas.Remove(this);
					}
					this._gvhd.Entity = value;
					if ((value != null))
					{
						value.ptdas.Add(this);
						this._magv = value.magv;
					}
					else
					{
						this._magv = default(string);
					}
					this.SendPropertyChanged("gvhd");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_ptda", Storage="_sinhvien", ThisKey="mssv", OtherKey="mssv", IsForeignKey=true)]
		public sinhvien sinhvien
		{
			get
			{
				return this._sinhvien.Entity;
			}
			set
			{
				sinhvien previousValue = this._sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sinhvien.Entity = null;
						previousValue.ptdas.Remove(this);
					}
					this._sinhvien.Entity = value;
					if ((value != null))
					{
						value.ptdas.Add(this);
						this._mssv = value.mssv;
					}
					else
					{
						this._mssv = default(string);
					}
					this.SendPropertyChanged("sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinhvien")]
	public partial class sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mssv;
		
		private string _matkhau;
		
		private string _hoten;
		
		private string _email;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _manhom;
		
		private EntitySet<ptda> _ptdas;
		
		private EntityRef<nhom> _nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnmanhomChanging(string value);
    partial void OnmanhomChanged();
    #endregion
		
		public sinhvien()
		{
			this._ptdas = new EntitySet<ptda>(new Action<ptda>(this.attach_ptdas), new Action<ptda>(this.detach_ptdas));
			this._nhom = default(EntityRef<nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NChar(16)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(150)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhom", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string manhom
		{
			get
			{
				return this._manhom;
			}
			set
			{
				if ((this._manhom != value))
				{
					if (this._nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhomChanging(value);
					this.SendPropertyChanging();
					this._manhom = value;
					this.SendPropertyChanged("manhom");
					this.OnmanhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_ptda", Storage="_ptdas", ThisKey="mssv", OtherKey="mssv")]
		public EntitySet<ptda> ptdas
		{
			get
			{
				return this._ptdas;
			}
			set
			{
				this._ptdas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhom_sinhvien", Storage="_nhom", ThisKey="manhom", OtherKey="manhom", IsForeignKey=true)]
		public nhom nhom
		{
			get
			{
				return this._nhom.Entity;
			}
			set
			{
				nhom previousValue = this._nhom.Entity;
				if (((previousValue != value) 
							|| (this._nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhom.Entity = null;
						previousValue.sinhviens.Remove(this);
					}
					this._nhom.Entity = value;
					if ((value != null))
					{
						value.sinhviens.Add(this);
						this._manhom = value.manhom;
					}
					else
					{
						this._manhom = default(string);
					}
					this.SendPropertyChanged("nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = this;
		}
		
		private void detach_ptdas(ptda entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = null;
		}
	}
}
#pragma warning restore 1591
