<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDoAn" Class="QuanLyDoAnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-JKDHQOJ\SQLEXPRESS;Initial Catalog=QuanLyDoAn;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyDoAnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DiemDA" Member="DiemDAs">
    <Type Name="DiemDA">
      <Column Name="MaDA" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MSSV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MSGV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="DoAn_DiemDA" Member="DoAn" ThisKey="MaDA" OtherKey="MaDA" Type="DoAn" IsForeignKey="true" />
      <Association Name="GiangVien_DiemDA" Member="GiangVien" ThisKey="MSGV" OtherKey="MSGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="NhomDA_DiemDA" Member="NhomDA" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomDA" IsForeignKey="true" />
      <Association Name="SinhVien_DiemDA" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiemDA" Member="DiemDA1s">
    <Type Name="DiemDA1">
      <Column Name="MaDA" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MSSV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MSGV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="DoAn_DiemDA1" Member="DoAn" ThisKey="MaDA" OtherKey="MaDA" Type="DoAn" IsForeignKey="true" />
      <Association Name="GiangVien_DiemDA1" Member="GiangVien" ThisKey="MSGV" OtherKey="MSGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="NhomDA_DiemDA1" Member="NhomDA" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomDA" IsForeignKey="true" />
      <Association Name="SinhVien_DiemDA1" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoAn" Member="DoAns">
    <Type Name="DoAn">
      <Column Name="MaDA" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiDA" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TenDA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DoAn_DiemDA" Member="DiemDAs" ThisKey="MaDA" OtherKey="MaDA" Type="DiemDA" />
      <Association Name="DoAn_DiemDA1" Member="DiemDA1s" ThisKey="MaDA" OtherKey="MaDA" Type="DiemDA1" />
      <Association Name="DoAn_PhieuDangKyDA" Member="PhieuDangKyDAs" ThisKey="MaDA" OtherKey="MaDA" Type="PhieuDangKyDA" />
      <Association Name="LoaiDA_DoAn" Member="LoaiDA" ThisKey="MaLoaiDA" OtherKey="MaLoaiDA" Type="LoaiDA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MSGV" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
      <Column Name="HoTenGV" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SLNhomQL" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="GiangVien_DiemDA" Member="DiemDAs" ThisKey="MSGV" OtherKey="MSGV" Type="DiemDA" />
      <Association Name="GiangVien_DiemDA1" Member="DiemDA1s" ThisKey="MSGV" OtherKey="MSGV" Type="DiemDA1" />
      <Association Name="GiangVien_NhomDA" Member="NhomDAs" ThisKey="MSGV" OtherKey="MSGV" Type="NhomDA" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDA" Member="LoaiDAs">
    <Type Name="LoaiDA">
      <Column Name="MaLoaiDA" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiDA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiDA_DoAn" Member="DoAns" ThisKey="MaLoaiDA" OtherKey="MaLoaiDA" Type="DoAn" />
    </Type>
  </Table>
  <Table Name="dbo.NhomDA" Member="NhomDAs">
    <Type Name="NhomDA">
      <Column Name="MaNhom" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MSSV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MSGV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HoTenSV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoLuongTV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="NhomDA_DiemDA" Member="DiemDAs" ThisKey="MaNhom" OtherKey="MaNhom" Type="DiemDA" />
      <Association Name="NhomDA_DiemDA1" Member="DiemDA1s" ThisKey="MaNhom" OtherKey="MaNhom" Type="DiemDA1" />
      <Association Name="GiangVien_NhomDA" Member="GiangVien" ThisKey="MSGV" OtherKey="MSGV" Type="GiangVien" IsForeignKey="true" />
      <Association Name="SinhVien_NhomDA" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDangKyDA" Member="PhieuDangKyDAs">
    <Type Name="PhieuDangKyDA">
      <Column Name="MSSV" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaDA" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HoTenSV" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayBatDay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DoAn_PhieuDangKyDA" Member="DoAn" ThisKey="MaDA" OtherKey="MaDA" Type="DoAn" IsForeignKey="true" />
      <Association Name="SinhVien_PhieuDangKyDA" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MSSV" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="SinhVien_DiemDA" Member="DiemDAs" ThisKey="MSSV" OtherKey="MSSV" Type="DiemDA" />
      <Association Name="SinhVien_DiemDA1" Member="DiemDA1s" ThisKey="MSSV" OtherKey="MSSV" Type="DiemDA1" />
      <Association Name="SinhVien_NhomDA" Member="NhomDAs" ThisKey="MSSV" OtherKey="MSSV" Type="NhomDA" />
      <Association Name="SinhVien_PhieuDangKyDA" Member="PhieuDangKyDAs" ThisKey="MSSV" OtherKey="MSSV" Type="PhieuDangKyDA" />
    </Type>
  </Table>
  <Table Name="dbo.ThuKyKhoa" Member="ThuKyKhoas">
    <Type Name="ThuKyKhoa">
      <Column Name="MSTK" Type="System.String" DbType="NChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
      <Column Name="HoTenThuKy" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>